### ISSUE TITLE
python-onbuild image layers

### ISSUE THREAD

**Issue by mort1k** [docker-library/python#126]
```
ONBUILD COPY requirements.txt /usr/src/app/
ONBUILD RUN pip install --no-cache-dir -r requirements.txt

ONBUILD COPY . /usr/src/app
```
why not be replaced by:

```
ONBUILD COPY . /usr/src/app
ONBUILD RUN pip install --no-cache-dir -r requirements.txt
```

**Comment by kevin-brown** [comment]
`requirements.txt` is less likely to change than `.` (any file in your app), so it allows installing the requirements to be cached (because the cache won't be busted every time).

These lines actually come directly from the [Dockerfile best practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/add-or-copy) page.

**Comment by mort1k** [comment]
tnx, i forgot about this nuance)
