### ISSUE TITLE
3.6.1 Missing

### ISSUE THREAD

**Issue by harsha-y** [docker-library/python#183]
From the dockerhub [README](https://hub.docker.com/_/python/) we should be able to pull `python:3.6.1-alpine`.

But we are running into the following error
```
$ docker pull python:3.6.1-alpine
Error response from daemon: manifest for python:3.6.1-alpine not found
$ docker pull python:3.6.1
Error response from daemon: manifest for python:3.6.1 not found
```

3.6.0 is the last know version that appears under [tags](https://hub.docker.com/r/library/python/tags/)

**Comment by cclauss** [comment]
A docker build of Python 3.6.1 (`docker build https://github.com/docker-library/python.git#:3.6/alpine`) generates the text:

```
+ gpg --batch --verify python.tar.xz.asc python.tar.xz
gpg: Signature made Tue Mar 21 07:48:11 2017 UTC using RSA key ID AA65421D
gpg: Good signature from "Ned Deily (Python release signing key) <nad@python.org>" [unknown]
gpg:                 aka "Ned Deily <nad@baybryj.net>" [unknown]
gpg:                 aka "keybase.io/nad <nad@keybase.io>" [unknown]
gpg:                 aka "Ned Deily (Python release signing key) <nad@acm.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
```

FYI: @ned-deily

**Comment by yosifkit** [comment]
> See a change merged here that doesn't show up on the Docker Hub yet? Check [the "library/python" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/python), especially [PRs with the "library/python" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fpython).

No, the Docker Store is not the source of truth, it just happens to be correct because the tag has not been pushed yet. The tags in the description on the Docker Hub is controlled by the content of the `library/` files in official-images.  We merged it with https://github.com/docker-library/official-images/pull/2774, but our build server locked up and we had to restart docker which then took a while (https://github.com/docker/docker/issues/31462) and we were not able to get back to it last night. The image is building and pushing right now, so it should be up in the next few minutes.

@cclauss that output is normal; since the python keys are the only keys imported, there is no way to verify it with a [web of trust](https://en.wikipedia.org/wiki/Web_of_trust).

**Comment by cclauss** [comment]
Thanks much for the great explanation.  It is clear to me now.  I will retry soon.

**Comment by einarf** [comment]
All is good now!
