### ISSUE TITLE
Should container use PEP 370?

### ISSUE THREAD

**Issue by italomaia** [docker-library/python#197]
I noticed that, by default, an python docker does not add the home dir for packages lookup. That can be seen with the command:

python -c "import sys; print(sys.path)"

Setting https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUSERBASE didn't change much. Am I missing something? Should this be active by default.

**Comment by yosifkit** [comment]
We don't have a specific place in the image that users might put their code.  By default the images run as root so that a user is free to install system dependencies and then change it to run as any user they need.  It would be up to the user to set `PYTHONUSERBASE` in their Dockerfile when they create a user or on `docker run` with `-e` to where they mount their code.
