### ISSUE TITLE
Gcc package not in the last build of the python:alpine container

### ISSUE THREAD

**Issue by Angatar** [docker-library/python#231]
Could you trigger the rebuild of the python:alpine container?
It seems there was an error with the "RUN set -ex"  command line (at L 23) since the gcc pakage and others in the same command were not installed in the container. 
Some of my tries to run the command inside the container have led to errors with checking the GPG key at ha.pool.sks-keyservers.net .The last tries I made seem to be ok, so it might have been an intermittent error from the keyserver ... so probably simply needs a rebuild

**Comment by yosifkit** [comment]
> To minimize image size, it's uncommon for additional related tools (such as `git` or `bash`) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the [`alpine` image description](https://hub.docker.com/_/alpine/) for examples of how to install packages if you are unfamiliar).
>
> \- https://github.com/docker-library/docs/blob/7c50b363b7d43a9a85b844bba901c52c73bc2916/python/README.md#pythonalpine

`gcc` is not left in the alpine based image in order to keep the size minimal.  It is removed once it is no longer needed: https://github.com/docker-library/python/blob/3f12f511910098f45951111aa5642fd935133afc/3.6/alpine3.4/Dockerfile#L84

The last build was successful: [![Build Status](https://doi-janky.infosiftr.net/buildStatus/icon?job=multiarch/amd64/python&build=32)](https://doi-janky.infosiftr.net/job/multiarch/amd64/python/32/)

**Comment by Angatar** [comment]
Thanks for the reply!
Indeed, I didn't noticed the package removal L84. Till my last pull of the container this week I used this python:alpine container (6 months old) for a python program that uses a C subroutine runed from the python:alpine container... this doesn't work anymore since my last pull. 
I well agree with the Alpine minimisation philosophy, that's why I selected this version of the container. 
I'll add the packages I need in my own Dockerfile so that I can ensure my program to work with the next python:alpine builds.
