### ISSUE TITLE
Any plans to add minideb support?

### ISSUE THREAD

**Issue by davesque** [docker-library/python#232]
I recently ran across Bitnami's minideb image: https://github.com/bitnami/minideb

Any reason or plans to add support for this as an alternative to alpine?

**Comment by yosifkit** [comment]
It would have to be an official image in order for an official image to be built `FROM` it.
> No official images can be derived from, or depend on, non-official images
>
> \- https://github.com/docker-library/official-images/tree/20ff8e7dc48bd583ceef76a9e847b53764a4ffb1#repeatability

The Debian images already have slim variants that exclude things like [docs, man pages, and locales](https://github.com/docker-library/docs/tree/212ed60a19b8b5454308b504fdcdf5d317f42b6f/debian#debiansuite-slim).  See also [debuerreotype](https://github.com/debuerreotype/debuerreotype), the reproducible, snapshot-based Debian rootfs builder that is used to build the Debian images, and its [`slimify` script](https://github.com/debuerreotype/debuerreotype/blob/76e05575e9bbb3bdec52fc3f56820828c425cea9/scripts/.slimify-excludes).

```console
$ docker images bitnami/minideb:stretch
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
bitnami/minideb     stretch             679c75d5b023        30 hours ago        53.6MB
$ docker images debian:stretch-slim
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
debian              stretch-slim        e004ce20eaba        11 days ago         55.2MB
```

We are swapping the slim images of python to be from the slim variants of Debian rather than regular ones (https://github.com/docker-library/python/pull/233).

**Comment by davesque** [comment]
Fair enough.  Thanks!
