### ISSUE TITLE
CPU architecture set to "armel" on ARM computers

### ISSUE THREAD

**Issue by DimaK-tracxpoint** [docker-library/python#240]
I have seen that default Python:2.7 image has its CPU architecture set to "armel" (ARMv4) even when running on ARMv7 machines like Raspberry. This complicates installation of an additional packages/drivers since not all of them are supported for this arch - and lowers the performance. 
When attaching to a container, its kernel correctly reports armv71 - so it seems to be an issue of dpkg/apt and Python infrastructure.
Is it possible to promote the default to "armhf"?

**Comment by yosifkit** [comment]
It is not the fault of the image, but the fault of Docker on pulling when using the manifest list; it just pulls the first image that matches `architecture` and doesn't use `variant` (like `v7`). See the upstream Docker issue: https://github.com/moby/moby/issues/34875.

For now, the workaround is to pull the specific image you want rather than relying on manifest lists: https://hub.docker.com/r/arm32v7/python/.

Related/duplicate issue https://github.com/docker-library/php/issues/518.

**Comment by DimaK-tracxpoint** [comment]
@yosifkit, thanks for clarifying. The original idea was to produce a Dockerfile that can be used on any supported architecture (since the code is anyway platform-neutral Python). Will follow the Docker issue you referred to for a resolution,
