### ISSUE TITLE
Missing folders in /usr/share/man

### ISSUE THREAD

**Issue by papaiatis** [docker-library/python#242]
Hi,

I just found that using the `python:3-slim` base image the folders `man1, man2 ... man9` are now missing under `/usr/share/man` which prevents me from installing some packages, for example `postgresql-client-9.4`. 
If I create these folder manually then there is no issue during installation.

I did some research and I believe this change is the root cause:
https://github.com/docker-library/python/commit/28490a60c628a76a2e5a35b986d687a9dcf3ae0e

Please consider creating these empty folders in the base image.

**Comment by yosifkit** [comment]
We would want to solve this at the Debian slim image level rather than every image that builds from it.  Linking related issue: https://github.com/debuerreotype/debuerreotype/issues/10.

**Comment by tianon** [comment]
This is an intentional feature of the Debian base image slim variants (which the Python slim variants are based on); the details are in the issue linked above. :+1:

(Closing since this isn't something we're going to fix in the Python image directly -- if anything here changes, it'd be in the Debian base image itself.)
