### ISSUE TITLE
Provide a 3.5 with pip 9.x release

### ISSUE THREAD

**Issue by darrenleeweber** [docker-library/python#284]
A lot of packages are broken on pip 10.x [1], please release a 3.5 on pip 9.x

e.g. https://github.com/docker-library/python/commit/49d4db584f3d8199fba353fd6f84b3aa4979a0ad#diff-aeb9571d9af89dbdb30b1183cf7c27f1

(Or am I missing something about how to specify a Dockerfile that depends on a git repo sha1?)

[1] e.g. https://github.com/Miserlou/Zappa/issues/1478#issuecomment-382449076

**Comment by agronholm** [comment]
What other packages are failing besides Zappa?

**Comment by tianon** [comment]
> A lot of packages are broken on pip 10.x [1], please release a 3.5 on pip 9.x

Sorry, but we only support the latest release of Pip -- I'd suggest contacting the authors of broken packages to ask them to fix whatever's broken.

> (Or am I missing something about how to specify a Dockerfile that depends on a git repo sha1?)

See https://github.com/docker-library/repo-info, which has exactly this type of information; sometimes it requires a little digging through Git history, but what you're looking for should be pretty easy to find.  For example, I cloned locally, then did a `git log -p repos/python/remote/3.5.md` (since you're interested in the last pushed image of `python:3.5` which included Pip 9.x), then did a text search for `PIP_VERSION=9` to find the most recent commit which included that text, which led me to:

https://github.com/docker-library/repo-info/commit/484c9d385f5af1e7f9d62d9e5499814223c5ad05

Looking at the file we're interested in at that commit (`repos/python/remote/3.5.md`), we can see that the content-addressable digest changed from `python@sha256:14bf86b8ca0e6195ea5d42bde5fc74b5c4c4821e08d63c8cb8d451197f0a274b` to `python@sha256:3600c4079864fa9e0d1bd9df760cac339fa30e3f375f34dab2f7e142f84105c7`, so if you pull `python@sha256:14bf86b8ca0e6195ea5d42bde5fc74b5c4c4821e08d63c8cb8d451197f0a274b`, you should get the older image which was Python 3.5 with Pip 9.x.
