### ISSUE TITLE
gcc not installed for 2.7-alpine3.7

### ISSUE THREAD

**Issue by xenide** [docker-library/python#292]
When installing with pip, I got a 

`    unable to execute 'gcc': No such file or directory `

So I inspected the image, and gcc couldn't be found when tried with sh, although we see this in the Dockerfile?

```              
apk add --no-cache --virtual .build-deps  \
		bzip2-dev \
		coreutils \
		dpkg-dev dpkg \
		gcc \
		gdbm-dev \
		libc-dev \
		linux-headers \
		make \
		ncurses-dev \
		libressl \
		libressl-dev \
		pax-utils \
		readline-dev \
		sqlite-dev \
		tcl-dev \
		tk \
		tk-dev \
		zlib-dev \
```

**Comment by tianon** [comment]
See https://github.com/docker-library/python/blob/f38c92b3fc2db507290e443b3e7b2844ebf16ab9/2.7/alpine3.7/Dockerfile#L77, where it's removed again (intentionally).

There are a lot of uses of this image that don't need `gcc`, so the Alpine variants exclude it by default for the sake of having a much smaller image (especially since it's so trivial for users to reinstall, but impossible for them to actually remove if we include it by default).

See also "`python:alpine`" on https://hub.docker.com/_/python/:

> To minimize image size, it's uncommon for additional related tools (such as `git` or `bash`) to be included in Alpine-based images.
