### ISSUE TITLE
slim tag changed to stretch from jessie

### ISSUE THREAD

**Issue by daveisfera** [docker-library/python#293]
The slim tag was changed to stretch from jessie and this feels like something that shouldn't have been done since it dramatically changes the meaning of this tag under people without any notification:
https://github.com/docker-library/official-images/commit/f200d7ffdeb698ad62802351dd9e023cad57a4bd#diff-051bb6df61b6c6e7f8c1868985011b07R43

**Comment by yosifkit** [comment]
This was partly done since Debian Jessie transitions from full support to [LTS support](https://wiki.debian.org/LTS) this month (https://wiki.debian.org/DebianReleases, ~June 6th, 2018) and so will get even fewer updates and fixes.

The only way we announce things is PRs to this repo and to docker-library/official-images. We added `*-slim-jessie` tags in October 2017 (https://github.com/docker-library/python/pull/233 and https://github.com/docker-library/official-images/pull/3607) so that this transition could happen. If users need to worry about the underlying OS release, then they should use the specific tags for the release of Python that they want. For example: `3.6.5-slim-jessie, 3.6-slim-jessie, 3-slim-jessie, slim-jessie`.

**Comment by daveisfera** [comment]
I agree that using the explicit tag is the right thing to do, but many Dockerfiles were made far before those tags existed. Jessie switching to LTS hardly seems like reason to change the definition of a tag and negates a big advantage of using docker in the first place (i.e. stability and reproducibility). Basically, people that want a newer version can use the stretch tags just as easily, if not easier, than existing users can use the jessie tag and then existing workloads wouldn't be busted without any user warning.

**Comment by tianon** [comment]
Just to follow up on this, "LTS" in Debian is a bit of a misnomer.  It's no longer explicitly supported by the Debian Security Team, and is a best-effort release from a number of paid contributors.  Essentially, if you care about a package in LTS, you should either pay for it to be maintained, or should step up and maintain it yourself (and this is the reason for the change).
