### ISSUE TITLE
Missing dependencies when using python:3

### ISSUE THREAD

**Issue by pslacerda** [docker-library/python#305]
I keep my images with the tag `python:3` because Python versioning says that 3.x are always compatible with previous 3.x versions. However latest update on tag `python:3` (that now is `3.7.0-stretch`) causes build failures on my requirements.txt.

> 
>   The headers or library files could not be found for zlib,
>   a required dependency when compiling Pillow from source.
> 

Because of this 3.7 was not ready to leave rc.

The workaround is simply change base image from `python:3` to `python:3.6`.

**Comment by pslacerda** [comment]
Yes, some symlinks (eg `libz.so` -> `libz.so.1` are missing and also the command `dpkg-architecture` that is called in https://github.com/python-pillow/Pillow/blob/5.2.x/setup.py#L736 to determine library directories.

**Comment by tao12345666333** [comment]
Yes, so it's not the image's issue, `dpkg-dev` package is not Python's runtime dependency.

**Comment by pslacerda** [comment]
I agree. Probably is more related to Pillow (because of `dpkg-architecture`) and/or debuerreotype (because of missing `libz.so` -> `libz.so.1`) and the image is in between.

**Comment by pslacerda** [comment]
So I'm closing this issue.

**Comment by pslacerda** [comment]
Answering the question:

Pillow needs `dpkg-archtecture` that was available in `python:3` but is not anymore. Installing `dpkg-dev` resolve the issue.

**Comment by yosifkit** [comment]
`dpkg-dev` has not existed in the python:3 image since https://github.com/docker-library/python/commit/cd1f11aa745a05ddf6329678d5b12a097084681b.  This is an oversight on our part and we will look to change the build dependency installation to be more like https://github.com/docker-library/php/pull/556 so that this won't happen in the future.

As far as the missing symlink for `libz.so.1`, that is a problem with your tool not using the ld config find where to look in Debian in general. Debian installs them to `/usr/lib/x86_64-linux-gnu/libz.so` and `/lib/x86_64-linux-gnu/libz.so.1` via the [`zlib1g-dev`](https://packages.debian.org/stretch/zlib1g-dev) and [`zlib1g`](https://packages.debian.org/stretch/zlib1g) packages, respectively (assuming x86-64 architecture). And both packages are installed the python:3.7-stretch and 3.6-stretch images:

```console
$ docker run --rm python:3.7-stretch dpkg -l | grep zlib
ii  zlib1g:amd64                       1:1.2.8.dfsg-5                 amd64        compression library - runtime
ii  zlib1g-dev:amd64                   1:1.2.8.dfsg-5                 amd64        compression library - development
$ docker run --rm python:3.6-stretch dpkg -l | grep zlib
ii  zlib1g:amd64                       1:1.2.8.dfsg-5                 amd64        compression library - runtime
ii  zlib1g-dev:amd64                   1:1.2.8.dfsg-5                 amd64        compression library - development
```

**Comment by pslacerda** [comment]
Glad that you fixed!

About the symlink, it was my mistake. I was looking for it on the wrong directories, but `ldconfig -p` correctly shows where it is installed.

Can I ask you what about https://github.com/docker-library/php/pull/556 do you plan to do? Save the list of packages installed on previous stages, install what is needed for the build and then autoremove them. There is something about it that I missed?

As curiosity, do you know if can be assumed that if `ldconfig` is provided by `glibc` then the cache will be at `/etc/ld.so.cache` and if the binary contents are stable across glibc versions and linux distributions? I know that it seems to holds true at Debian and Fedora, but I'm not sure about other distributions.
