### ISSUE TITLE
python:3.6-alpine3.7 -  /etc/ssl/cert/ folder in 3.6-alpine3.7

### ISSUE THREAD

**Issue by brandonawells** [docker-library/python#324]
I'm deploying a docker image onto aws  and  i'm getting the following error:

`Error: Failed to list store contents: RequestError: send request failed
caused by: Post https://ssm.ca-central-1.amazonaws.com/: x509: failed to load system roots and no roots provided
`
Older containers work fine, but the recent builds don't have /etc/ssl/cert/.

My image is based on `python:3.6-alpine3.7`

**Comment by wglambert** [comment]
Caused by https://github.com/docker-library/python/commit/e078edc2b84b41a5aa3457f2c316f45ea02a28eb

**Comment by brandonawells** [comment]
Thanks @wglambert 

@JayH5 I'm deploying this onto AWS ECS (their container orchestration service). I get that error in my logs when the container attempts to start up.

**Comment by JayH5** [comment]
@brandonawells I mean what software is the container running? Any chance you can do a `pip freeze`? Thanks.

Anyway, I guess there is some software that wants those CA certs at that path and we should maybe install the `ca-certificates` package again :( it's not the whole of that commit that needs reverting, though.

**Comment by brandonawells** [comment]
I found a comment about amazon aws's ecs-agent:

> We store the CA certificates in /etc/ssl/certs/ca-certificates.crt inside the image

https://github.com/aws/amazon-ecs-agent/issues/1196#issuecomment-359534316

Did the alpine image ever store a cert at `/etc/ssl/certs/ca-certificates.crt`? I haven't noticed this issue before today, so Im just trying to understand it as well.

**Comment by brandonawells** [comment]
The container is running a django-wagtail application. We don't have any specific cert related items in it. So I believe this is ecs-agent.

**Comment by brandonawells** [comment]
@JayH5 pip freeze
`
beautifulsoup4==4.6.0
boto==2.46.1
boto3==1.4.4
botocore==1.5.27
certifi==2018.1.18
chardet==3.0.4
dj-database-url==0.4.2
Django==1.11.10
django-htmlmin==0.10.0
django-log-request-id==1.3.2
django-modelcluster==3.1
django-recaptcha==1.3.1
django-storages==1.5.2
django-taggit==0.22.2
django-treebeard==4.2.0
djangorestframework==3.6.4
docutils==0.14
gunicorn==19.7.1
html5lib==0.999999999
idna==2.6
jmespath==0.9.3
olefile==0.44
Pillow==5.0.0
psycopg2==2.7.3.1
python-dateutil==2.7.3
python-http-client==3.0.0
pytz==2018.3
raven==6.4.0
requests==2.18.4
s3transfer==0.1.13
sendgrid==3.6.5
sendgrid-django==4.0.4
six==1.11.0
Unidecode==1.0.22
urllib3==1.22
wagtail==1.13.1
wagtail-django-recaptcha==0.2
webencodings==0.5.1
WebOb==1.8.2
Willow==1.0
wsgi-basic-auth==1.1.0
`

**Comment by JayH5** [comment]
@brandonawells thanks. `/etc/ssl/certs/` was present in the Alpine 3.7+ images before e078edc as `ca-certificates` was installed.

It seems it is actually some Golang code running in the container that is producing that error, not Python code.

I don't know much about ECS but I guess the ecs-agent is inserted into the container and is failing because it's written in Go which builds its own certificate bundle from the contents of `/etc/ssl/certs` which is not present because `ca-certificates` is now not installed (...so I guess I am just _finally_ understanding what you were saying).

I guess for now if possible you could install `ca-certificates` yourself. I _think_ it would be a good idea for us to install it again in these images, since a bunch of software seems to expect those files to be there, even if most Python software does not 😿.

**Comment by brandonawells** [comment]
Thanks @JayH5!

**Comment by jcoetzee** [comment]
Bumping an old issue but just ran into similar on a different container and my Googling led me here. FWIW, I found that it wasn't strictly necessary to revert not installing `ca-certificates` - it's a bit hacky but I just symlinked `/etc/ssl/cert.pem` to `/etc/ssl/certs/ca-certificates.crt` and it's working my side.
