### ISSUE TITLE
arm32v6 builds are failing

### ISSUE THREAD

**Issue by bskaggs** [docker-library/python#329]
It looks like `arm32v6/python:*` hasn't been successfully built for four months.  Any ideas how to try to fix it from the [console output of the last build](https://doi-janky.infosiftr.net/job/multiarch/job/arm32v6/job/python/160/consoleFull)?

**Comment by tianon** [comment]
I'm afraid this is along the same lines as https://github.com/docker-library/php/issues/648, https://github.com/nodejs/docker-node/issues/751, https://github.com/docker-library/golang/issues/196, etc. :disappointed:

(TL;DR: The hardware we're currently performing `arm32v6` builds on doesn't support some esoteric instruction that Alpine is now using, which causes the builds to fail.  We have a workaround, but for things which need heavy compilation like Python does, it isn't scalable since it's an emulated VM, and the real arm32 hardware we have access to isn't really performant enough to even consider.)

**Comment by tianon** [comment]
See https://github.com/docker-library/oi-janky-groovy/commit/5141c15b1ba4ced1617a6150f625e46d573d62f9 :tada: :cake: :metal:
