### ISSUE TITLE
Unsatisfiable constraints when installing postgresql-dev on python:3.8-alpine

### ISSUE THREAD

**Issue by vitor-tadashi** [docker-library/python#344]
Attempting to add postgresql-dev via APK in order to use this image as a base for a Python application yields an unsatisfiable constraints error around the versions of libssl and openssl.

Create docker file with
```
FROM alpine:3.8

EXPOSE 8080

# Copy python requirements file
COPY requirements.txt /tmp/requirements.txt

RUN apk add --no-cache \
    alpine-sdk \
    python3 \
    python3-dev \
    libffi-dev \
    openssl-dev \
    gcc \
    postgresql-dev \
    make \
    g++ \
    nginx \
    uwsgi \
    uwsgi-python \
    supervisor && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    pip3 install -r /tmp/requirements.txt && \
    rm /etc/nginx/conf.d/default.conf && \
    rm -r /root/.cache

# Copy the Nginx global conf
COPY nginx.conf /etc/nginx/
# Copy the Flask Nginx site conf
COPY clu-api-nginx.conf /etc/nginx/conf.d/
# Copy the base uWSGI ini file to enable default dynamic uwsgi process number
COPY uwsgi.ini /etc/uwsgi/
# Custom Supervisord config
COPY supervisord.conf /etc/supervisord.conf

ADD . /opt/clu-api
WORKDIR /opt/clu-api

CMD ["/usr/bin/supervisord"]
```

**Comment by yosifkit** [comment]
Seeing that you aren't actually using the python image we provide from this repo (your `FROM` is `alpine:3.8`, not `python:3.7-alpine3.8`), this is not a problem with our image. Closing.

----------------

On a side note, since I know a little about Alpine's packaging and that they switched all packages they build to use `libressl`, I can say that [`postgresql-dev`](https://pkgs.alpinelinux.org/package/v3.8/main/x86_64/postgresql-dev) depends on `libressl-dev` which cannot be installed at the same time as `openssl-dev`.

So you'll need to adjust to using `libressl-dev` or use an older, unsupported version of Alpine (3.4 or earlier) that used `openssl-dev` for `postgresql-dev`.
