### ISSUE TITLE
Can not pull i386/python

### ISSUE THREAD

**Issue by deniswvieira** [docker-library/python#376]
Hey there,

I am not able to pull i386/python (or any related tag).
```
»»» docker pull i386/python:3.5
3.5: Pulling from i386/python
no matching manifest for unknown in the manifest list entries
```

I am able to pull i386/python:3.5-slim or -alpine

My system:
 ```
»»» lsb_release -a
No LSB modules are available.
Distributor ID: neon
Description:    KDE neon User Edition 5.13
Release:        16.04
Codename:       xenial

4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Best regards,
Denis

**Comment by tianon** [comment]
This is likely due to https://github.com/moby/moby/issues/34875 (since your host machine isn't actually a 32bit machine and these tags are manifest lists); see https://github.com/docker-library/golang/issues/249#issuecomment-438478127 for a similar discussion regaring the `golang` image.  You'll either need to use https://github.com/docker-library/repo-info to get the digest of the underlying image itself or switch to one of the tags that aren't listed as "Shared Tags" on the image description.
