### ISSUE TITLE
Python 3.8 Stretch Image

### ISSUE THREAD

**Issue by GrahamCampbell** [docker-library/python#428]
Are we going to get a stretch image? I need this because I need the to use the image in order to link against an older version of glibc.

**Comment by GrahamCampbell** [comment]
Yes, my situation is perhaps a little bespoke. I am packaging a binary (using https://www.pyinstaller.org/) for distribution onto an Ubuntu 18.04 LTS machine, using the Python docker images for the packaging process. The problem is that the newest Debian has a too new version of glibc, so my binary is linked against that, rather than an older version. Binaries linked against old versions work fine with newer versions, but not the reverse.

**Comment by GrahamCampbell** [comment]
> Pretty sure you only really need to change the FROM buildpack-deps:buster to FROM buildpack-deps:stretch to do so, I think?

I suspect you are right. I suppose my reason for posting an issue was to see if there was interest in having an official Stretch image, or if the maintainers are set on dropping it.

**Comment by tianon** [comment]
I wouldn't say we're necessarily completely set against adding it, but we would prefer to have a pretty strong justification for it (and I agree that this particular use case sounds a bit bespoke).

**Comment by impredicative** [comment]
@tianon I will give a justification. Many HTTPS certs are deemed invalid by `urllib` if `buster` (Debian 10) is used. They're continued to deemed valid if `stretch` (Debian 9) is used. I want to give those websites more time to fix their HTTPS certs. I believe the EOL of `stretch` is 2020-07-06. I can personally use the `python:3.8-slim-stretch` image.

**Comment by daveisfera** [comment]
@impredicative this is typically not a certificate issue but caused by the fact that `buster` [dropped support for TLS 1.0 and 1.1](https://lists.debian.org/debian-devel-announce/2017/08/msg00004.html)

**Comment by yosifkit** [comment]
@impredicative and @daveisfera, is it really because the server only uses TLS 1.0 or 1.1? Openssl in Buster also requires longer keys by default and that can easily be lowered as we have done for running tests in [memcached](https://github.com/docker-library/memcached/blob/8376d3e6597b15dab660809097c4c5ec4ba91c9a/debian/Dockerfile#L60-L61). See also https://bugs.debian.org/927461.

**Comment by impredicative** [comment]
@yosifkit Thanks; that really did help. Motivated by your linked Dockerfile, I added `RUN sed -i 's/@SECLEVEL=2/@SECLEVEL=1/' /etc/ssl/openssl.cnf` to [my Dockerfile](https://github.com/impredicative/irc-url-title-bot/blob/cbd1798d86d4871337c600a7f4dee6b2d0712d0a/Dockerfile#L6) which uses `python:3.8-slim-buster`. I can now read a URL such as [this](https://www.nims.go.jp/eng/news/press/2019/11/201911110.html) which I couldn't earlier.

**Comment by johnthagen** [comment]
I just wanted to echo that I too wanted to use a newer Python version on `stretch` in order to build PyInstaller binaries that could target an older Linux distributions (such as Ubuntu 18.04) while using a more modern version of Python (such as 3.8).

The challenge with using Ubuntu 18.04 as the base image is that you are stuck to Python 3.6 unless you resort to a third-party PPA such as deadsnakes.

Keeping everything to an official Python Docker image seemed safer/simpler.

**Comment by johnthagen** [comment]
https://github.com/docker/compose/issues/8048 is a good example about why supporting newer Pythons on older Debian releases is helpful. `docker-compose` wanted to upgrade their supported Python version, but had to fall back to 3.7 because of glibc compatibility for their binaries.

**Comment by JayH5** [comment]
The glibc incompatibility is specifically the problem that [manylinux](https://github.com/pypa/manylinux) wheels aim to solve. That's for wheels, not executables, but the same principles could be applied. There are also Docker images available for building manylinux wheels that could possibly be reused as environments to build executables.
