### ISSUE TITLE
Upgrade gcc version on python:3.7.2-slim

### ISSUE THREAD

**Issue by NicoLivesey** [docker-library/python#462]
Hi,

In order to build an API with ML models, I need to install a specific gcc version (7.3.0 or above 5 at least). What would be the good practice to do it on this Image ?

Thank you in advance !

**Comment by wglambert** [comment]
You would want to install gcc, build the necessary components, then uninstall gcc in the same layer (uninstalling in a different `RUN` line will inflate the image size)
Something like https://github.com/docker-library/python/issues/447#issuecomment-571805118 or https://github.com/docker-library/python/issues/396#issuecomment-492350706

For additional help you could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by NicoLivesey** [comment]
Yup thank you for the answer, that was way easier that I expected :D
