### ISSUE TITLE
Lessons

### ISSUE THREAD

**Issue by vadiyan** [docker-library/python#463]
Python3

**Comment by vadiyan** [comment]
records = [
    ('foo', 1, 2),
    ('bar', 'hello'),
    ('foo', 3, 4),
]

def do_foo(x, y):
	print('foo', x, y)
def do_bar(s):
	print('bar', s)
for tag, *args in records:
	if tag == 'foo':
		do_foo(*args)
	elif tag == 'bar':
		do_bar(*args)

**Comment by wglambert** [comment]
Is this a misfiled issue?

Otherwise can you describe the issue and give all the commands you ran and any relevant contextual information or files for reproducing it?

**Comment by tianon** [comment]
This is the repository for the `python` Docker image found on Docker Hub (https://hub.docker.com/_/python).

It sounds like you might be looking for general Python help, for which you'd be better off finding an appropriate Python user forum or StackOverflow, but you'll also want to spend some time making sure your question is concise and complete before making further attempts elsewhere.

If it turns out you need further assistance with the `python` (or any other) Docker image, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
