### ISSUE TITLE
error installing postgresql-dev with python:3.8.2-alpine

### ISSUE THREAD

**Issue by domdinicola** [docker-library/python#478]
using  python:3.8.2-alpine I get unsatisfiable constraints when installing postgresql-dev
any advice?

```Sending build context to Docker daemon  94.09MB
Step 1/30 : FROM python:3.8.2-alpine as builder
 ---> d5e5ad4a4fc0
Step 2/30 : RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories
 ---> Using cache
 ---> f7e2e8d8c33a
Step 3/30 : RUN apk update
 ---> Using cache
 ---> 7893a9176908
Step 4/30 : RUN apk add --upgrade apk-tools
 ---> Using cache
 ---> 43554075b7c2
Step 5/30 : RUN apk add     --update alpine-sdk
 ---> Using cache
 ---> b193f988b3ce
Step 6/30 : RUN apk add postgresql-dev
 ---> Running in 530e765e6143
ERROR: unsatisfiable constraints:
  libffi-3.2.1-r6:
    conflicts: libffi-3.3-r2
    satisfies: llvm9-libs-9.0.0-r1[so:libffi.so.6]
               .python-rundeps-20200324.025755[so:libffi.so.6]
  libffi-3.3-r2:
    conflicts: libffi-3.2.1-r6
    satisfies: llvm10-libs-10.0.0-r2[so:libffi.so.7]
The command '/bin/sh -c apk add postgresql-dev' returned a non-zero code: 9
Makefile:11: recipe for target 'release' failed
make: *** [release] Error 9
``

**Comment by wglambert** [comment]
The edge repo's you're adding have `libffi-3.3-r2`, but it conflicts with the already installed `libffi-3.2.1-r6` which is a dependency for Python

https://github.com/docker-library/python/blob/6ceac803dd9c260a2c530543f0806796183715c0/3.8/alpine3.11/Dockerfile#L50

Not using the edge repo works fine for installing `postgresql-dev`

Closing since this isn't an issue with the image and questions like these should be asked over at [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
