### ISSUE TITLE
Add python3-dev fake package on debian images

### ISSUE THREAD

**Issue by emonty** [docker-library/python#480]
When installing binary depends in support of installing python packages with C-dependencies, sometimes python3-dev needs to get pulled in as part of the dependency chain. Of course, distro python3-dev provides a set of headers which aren't what is being used by python in the image. It's fine - this image puts stuff in /usr/local which wins, but it's a total waste in transitive depend installation when the image already has headers.

I've got a builder image where I make a fake equivs python3-dev package and install it so that apt believes python3-dev exists:

https://opendev.org/opendev/system-config/src/branch/master/docker/python-builder/Dockerfile#L20-L24
https://opendev.org/opendev/system-config/src/branch/master/docker/python-builder/Dockerfile#L30-L35
https://opendev.org/opendev/system-config/src/branch/master/docker/python-builder/python3-dev.control
relevant snippet:
```
RUN apt-get update \
  && apt-get install -y curl equivs \
  && rm -rf /var/lib/apt/lists/*
COPY python3-dev.control /tmp/python3-dev.control
RUN equivs-build /tmp/python3-dev.control
RUN dpkg -i /tmp/python3-dev_4.0.0_all.deb \
  && rm /tmp/python3-dev_4.0.0_all.deb
```
python3-dev.control:
```
Section: misc
Priority: optional
Standards-Version: 2.3.3

Package: python3-dev
# Set the version to 4.0.0 so that it'll always be a greater
# version than any version of python3-dev in the archive.
Version: 4.0.0
Section: mail
Maintainer: Some Body
Architecture: all
Description: Dummy python3-dev package
```

Would you have any interest in a PR to upstream that or something like it? Happy to also do the same thing pretty easily for the normal python package too.

**Comment by tianon** [comment]
It's not an exact duplicate, but this is definitely related to https://github.com/docker-library/python/issues/43 and https://github.com/docker-library/python/issues/457, and I think https://github.com/docker-library/python/issues/457#issuecomment-598466852 applies pretty directly:

> The versions of Python in the repositories of the stable Alpine and Debian releases are going to (usually intentionally) lag behind upstream's "latest and greatest" which is the biggest reason we compile from source in this particular case.

Practically, what this means is that if we were to "pretend" we provide the standard Debian `python3` packages, other Debian packages would use our Python implementation instead of Debian's, and would likely have somewhere between subtle and horrible/crashy bugs.  There are a lot of packages within Debian which would likely need to be rebuilt to actually use our Python installation properly.

Ideally, we would provide APT pinning to exclude Debian's Python packages (like is done in the PHP image; https://github.com/docker-library/php/blob/f6170fb3db7826cb8e67b4a8dc56602c1a163a97/Dockerfile-debian.template#L3-L10), but unfortunately there are a lot of system-level tools that are written in Python, and any of these proposed solutions would break those (which we don't want to do). :disappointed:

**Comment by emonty** [comment]
Great point! Yeah - the compiling from source is one of the things I love about these images, and from my use it very much means I never ever want anything to pull in system python. But - that's a great point about system tools and definitely not breaking people or those tools is a solid choice.
