### ISSUE TITLE
python3.8 includes also 3.7

### ISSUE THREAD

**Issue by horpto** [docker-library/python#486]
image: python3.8-buster

If I exec `python3` all works fine and it gets python3.8
But command `/usr/bin//python3` calls `python3.7.3`. It can be important for some scripts.

**Comment by wglambert** [comment]
See https://github.com/docker-library/python/issues/253#issuecomment-354845818 https://github.com/docker-library/python/issues/174#issuecomment-382460956
>This is kind of an unfortunate side-effect of our use of buildpack-deps in the non-slim variants


We have made sure that the `PATH` is set appropriately so that the Python compiled in the Dockerfile is preferred.
https://github.com/docker-library/python/blob/3ebdcfdf001fb2a5b6c4d283379371f7d0537436/3.8/buster/Dockerfile#L9-L10

**Comment by horpto** [comment]
@wglambert 
Ok, thanks, I get it. Seems it's popular issue. Maybe should it be included in readme on dockerhub ?

**Comment by duebbert** [comment]
Yes, +1 to include this in the Readme! 

We ran into exactly this issue when using image 3.7-slim-buster. All worked well for months until suddenly our entrypoint failed to find packages after a new build. Turned out we were using /usr/bin/python3. It is nowhere documented that you must not use `/usr/bin/python*` but should use the path-less or `/usr/loca/bin/python*` versions.
