### ISSUE TITLE
Include default non-root user

### ISSUE THREAD

**Issue by bkief** [docker-library/python#487]
I'd like to propose to adding a default non-root user to the python builds to aide in out-of-the-box security. Otherwise I am frequently creating a custom dockerfile just to add the user. If the community agrees I can work on a PR.

**Comment by tianon** [comment]
In most cases, I'm able to accomplish this with `--user 1000:1000` or similar (most software doesn't need an entry in `/etc/passwd`, and Docker certainly doesn't), so it seems kind of prescriptive of us to include a default user that we can't set as the default (like we can in other images, like `php` due to how they run), so it'll ultimately be up to users to choose to use it anyhow. :confused:
