### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found

### ISSUE THREAD

**Issue by gayatriprasad** [docker-library/python#518]
Hello, 

This is the error I have encountered. 

ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/user/anaconda3/lib/python3.8/site-packages/bpy.so)

Can you help me with this ?

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/tree/master/python#pythonversion-alpine
>The main caveat to note is that it does use musl libc instead of glibc

Questions like these should be asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by gayatriprasad** [comment]
Thank you. Closing the issue.
