### ISSUE TITLE
some of python-Alpine based application packages failed to compile

### ISSUE THREAD

**Issue by AhmadAlKhaldi86** [docker-library/python#524]
Can you add g++ Compiler into the base image.  gcc is installed - but some of application dependacies requrired g++ .

**Comment by wglambert** [comment]
It's 48MB, which is double the size of the Alpine image
https://pkgs.alpinelinux.org/package/v3.12/main/x86/g++

The common workflow is you'd want to install it, then compile your packages, and then in the same `RUN` layer uninstall it so your image size doesn't increase unnecessarily
An example here https://github.com/docker-library/python/issues/488#issuecomment-632744287

Additionally you could use the standard standard `python` variant that has g++ in the image but is 882MB
https://github.com/docker-library/docs/tree/master/python#image-variants

Questions like these should be asked over at [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by yosifkit** [comment]
>To minimize image size, it's uncommon for additional related tools (such as `git` or `bash`) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile
>
>[docker hub docs](https://github.com/docker-library/docs/tree/5ec0c227da483365b0a181d7d4610565617ef0b6/python#pythonversion-alpine)

Neither `g++` nor `gcc` is included in the Alpine based images:

```console
$ docker run -it --rm python:alpine sh
/ # apk info
WARNING: Ignoring APKINDEX.2c4ac24e.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.40a3604f.tar.gz: No such file or directory
busybox
alpine-baselayout
alpine-keys
libcrypto1.1
libssl1.1
ca-certificates-bundle
libtls-standalone
ssl_client
zlib
apk-tools
scanelf
musl-utils
libc-utils
ca-certificates
libffi
libintl
ncurses-terminfo-base
ncurses-libs
libbz2
sqlite-libs
xz-libs
musl
expat
gdbm
libtirpc-conf
krb5-conf
libcom_err
keyutils-libs
libverto
krb5-libs
libtirpc
libnsl
libuuid
readline
.python-rundeps
```
