### ISSUE TITLE
slim-buster image doesn't work properly (after 3.9)

### ISSUE THREAD

**Issue by MikkelHJuul** [docker-library/python#547]
works:
```docker
FROM python:3.8-slim-buster

RUN pip install confluent_kafka
```
does not work
```docker
FROM python:3.9-slim-buster

RUN pip install confluent_kafka
```
throws errors on missing gcc
when after installing gcc, it throws errors on librdkafka, then after installing that you try installing confluent_platform. THEN you figure out that it's the python docker image thats the issue, not your dependencies...

attachment to document my steps to reproduce (using a gitlab-runner and gcr.io/kaniko)

[error.log](https://github.com/docker-library/python/files/5369526/error.log)

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/tree/master/python#pythonversion

For `python:slim` you'll want to install gcc, do `pip install`, and then uninstall gcc in the same layer https://github.com/docker-library/python/issues/488#issuecomment-632744287

**Comment by tianon** [comment]
It sounds like `confluent_kafka` might not support Python 3.9 (yet?)

**Comment by wglambert** [comment]
Yeah seems that way if the [latest release](https://github.com/confluentinc/confluent-kafka-python/releases) is July and 3.9 was released October 5. And the gcc error would be due to the manylinux1 wheels not being compatible, such as if the version is unsupported

I don't see anything in their [issues mentioning 3.9](https://github.com/confluentinc/confluent-kafka-python/issues?q=is%3Aissue+is%3Aopen+3.9)

**Comment by MikkelHJuul** [comment]
I will redirect this issue to confluent_kafka instead. The error messages just sound relatively system-ish, to have been issues with confluent, I apologize for hitting the wrong forum.
