### ISSUE TITLE
Issues with datetime module on debian buster based images

### ISSUE THREAD

**Issue by szymonpolinkiewicz** [docker-library/python#548]
Hi, I have some issues with datetime module on debian-based images.
Example:
```
$ docker run -it python:3.9-buster python

>>> import datetime
>>> ts = datetime.datetime(1,1,1)
>>> ts.strftime('%Y')
'1'
```

Expected output is `0001`.
The issue is reproducible also on 3.8.1-buster and 3.8.5-buster images (I didn't check any other versions).

I've checked alpine based images and it works as expected.

**Comment by tianon** [comment]
This is curious, but I'm not sure this is actually a bug in our image -- I thought it might be locale related, so I installed the `locales` package and generated the `en_US.UTF-8` locale which didn't change anything about the output.  Then I tried Python 3 from Debian's packages and it has the exact same behavior, so this appears to be the "intentional" upstream behavior?

(Hilariously, Python 2 instead complains: `ValueError: year=1 is before 1900; the datetime strftime() methods require year >= 1900` :smile:)

Trying `/usr/bin/python3` on my Debian Buster host system (not a container) has the exact same behavior.
