### ISSUE TITLE
RaspberryPi building docker error while installing ssh2

### ISSUE THREAD

**Issue by invictusro** [docker-library/python#549]
Hello guys so I do have a RaspberryPi and I'm trying to build a docker container that has python script with Flask and I'm using some libraries, the other libraries are succesfully installed but this one doesn't seems to work:

> Running setup.py install for ssh2-python: started
> Running setup.py install for ssh2-python: finished with status 'error'

Also, this is something that the error includes and I think that it might be the reason:

>    /bin/sh: 1: cmake: not found

That's how my dockerfile looks like:

> FROM cseelye/rpi-nginx-uwsgi-flask
> MAINTAINER Carl Seelye <cseelye@gmail.com>
> 
> COPY exampleapp /app
> RUN sudo pip install -U -r /app/requirements.txt
> 

Requirements are the following:

> pip==18.1.0
> mysql-connector==2.2.9
> Flask==1.0.2
> getmac==0.8.2
> ssh2-python==0.19.0

 The flask python app succesfully worked on local. I have tried several solutions from stack and so on but none of them seemed to work. Anyone have any ideea ?

**Comment by tianon** [comment]
I'm a little confused here -- `FROM cseelye/rpi-nginx-uwsgi-flask` isn't the image you've filed this on?

I think you probably meant to file this at https://github.com/cseelye/rpi-nginx-uwsgi-flask.

**Comment by invictusro** [comment]
> I'm a little confused here -- `FROM cseelye/rpi-nginx-uwsgi-flask` isn't the image you've filed this on?
> 
> I think you probably meant to file this at https://github.com/cseelye/rpi-nginx-uwsgi-flask.

Hmm not sure how it works but actually it installs the requirements from my local file and there is where I’m getting my error

**Comment by wglambert** [comment]
`cseelye/rpi-nginx-uwsgi-flask` is based on Raspbian which uses https://www.piwheels.org by default. So if you were going to use a different image (such as this one) then you'd want to configure `pip.conf`
Also that Dockerfile is from 2016 and only has Python 2.7 which is now deprecated, perhaps one of these factors might be the cause of the issue

I'm going to close since this issue isn't related to our image.
You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). As these repos aren't really a user-help forum
