### ISSUE TITLE
Python 3.5 deprecation

### ISSUE THREAD

**Issue by joao-p-marques** [docker-library/python#556]
Python 3.5 has been deprecated, and every time you run `pip install` in a `python:3.5-*` based container, you get the following warning:
```
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
```
In our case, we need to keep using Python 3.5 in our images, and rebuild them often. 

When pip drops support for Python 3.5, what will happen to pip inside those docker images? Will it remain as the current version (20.2.3)? 

OTOH, I noticed the Dockerfiles for said versions have been removed (https://github.com/docker-library/python/commit/93ddb24e33564a4f70f945a9fe603488bfd3a31e). Will the images remain available in Docker Hub? For how long?

**Comment by yosifkit** [comment]
Since the Dockerfiles have been removed (and references dropped from docker-library/official-images), we won't ever touch the built images and they will remain indefinitely available to pull from Docker Hub (related: https://github.com/docker-library/official-images/issues/8552#issuecomment-679251691).
