### ISSUE TITLE
schema.headers warning in python:3.8-slim

### ISSUE THREAD

**Issue by christopherpickering** [docker-library/python#608]
Running the 3.8 slim docker container produces warnings when doing pip install:

```dockerfile
FROM python:3.8-slim
RUN python -m pip install --disable-pip-version-check --quiet tox
```

Output:

```sh
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/include/python3.8/UNKNOWN
sysconfig: /usr/local/include/python3.8
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
```
how can the image be fixed?

from issue https://github.com/pypa/pip/issues/9617

**Comment by tianon** [comment]
Our Python installation process amounts to "download Python sources, `./configure && make && make install`, install PIP directly from `get-pip.py`", so https://github.com/pypa/pip/issues/9617#issuecomment-826108606 confuses me a lot (if a pretty stock `./configure` gives us a "misconfigured" Python by default, we're all in a heap of trouble, I'd think?).

That being said, I think from both the OP there and specifically https://github.com/pypa/pip/issues/9617#issuecomment-826152560, it's pretty clear this warning is currently very harmless and should simply be ignored until there's a new release out that might silence it (likely 21.1.1).  It looks like https://github.com/pypa/pip/pull/9838 probably handles the specific case we have (I'm not going to say "fix" here because frankly, nothing is actually broken, as made very clear repeatedly over in https://github.com/pypa/pip/issues/9617).

**Comment by christopherpickering** [comment]
Thanks for the comments! I really was posting here because he had locked the discussion on the main thread :) My gitlab-ci was crashing on the warning.

**Comment by tianon** [comment]
Your CI _crashed_ on the warning?? :grimacing:

Are you specifically grepping the logs for warnings and erroring out, or did this somehow cause a failure?

**Comment by lmeyerov** [comment]
We caught this too. A lot of teams prefer to run software without warnings, such as to head off security surprises, so false alarms in official repos is surprising.

**Comment by christopherpickering** [comment]
> Your CI _crashed_ on the warning?? 😬
> 
> Are you specifically grepping the logs for warnings and erroring out, or did this somehow cause a failure?

😁 just looked closer, there were other issues in there as well.. the ci normally passed so I jumped on this one first. Thanks for correcting 😄

**Comment by tianon** [comment]
Given https://github.com/pypa/pip/issues/9617#issuecomment-830053765, today's pip bump should've resolved this. :+1:
