### ISSUE TITLE
Missing matching shared libraries

### ISSUE THREAD

**Issue by netrix** [docker-library/python#610]
I'm creating a library in C++ for which I'm adding bindings to python using the C interface. To do this I'm using `python-dev` package to bulid the Python package. 

I've noticed that while using proper docker image (i.e. `python: 3.8-slim`) to target each python version (i.e. python 3.8) it is creating a package for that version but since `python-dev` relies on the system version (buster) it is always linked to python-3.7 shared libraries because all versions of Python images use the same `buster` image as a a base) 

is it an oversight or it is correct and I'm doing something wrong?

**Comment by wglambert** [comment]
Yeah since Python is built from source in this image then installing `python3-dev` has Python from the repo's as a dependency which gets you two Pythons
PHP has the same issue but for that image the Debian PHP packages are blocked https://github.com/docker-library/php/pull/542

Although for Python: https://github.com/docker-library/python/issues/571#issuecomment-760534252
>this is way too dangerous because there are so many system-level packages/tools that use Python that we can't reasonably block it (unlike PHP).

**Comment by Jattprogrammer** [comment]
Fuck off
