### ISSUE TITLE
Broken supervisor package in 3.9-alpine - 3.9.6 release

### ISSUE THREAD

**Issue by simone-gasparini** [docker-library/python#624]
supervisor package commands will not start in python:3.9-alpine image, throwing a `ModuleNotFoundError`
I've noticed that `apk add supervisor` command install python 3.9.5 instead of 3.9.6

Step to reproduce:
```
/ # apk add supervisor
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
(1/11) Installing libgcc (10.3.1_git20210424-r2)
(2/11) Installing libstdc++ (10.3.1_git20210424-r2)
(3/11) Installing mpdecimal (2.5.1-r1)
(4/11) Installing python3 (3.9.5-r1)
(5/11) Installing py3-ordered-set (4.0.2-r1)
(6/11) Installing py3-appdirs (1.4.4-r2)
(7/11) Installing py3-parsing (2.4.7-r2)
(8/11) Installing py3-six (1.15.0-r1)
(9/11) Installing py3-packaging (20.9-r1)
(10/11) Installing py3-setuptools (52.0.0-r3)
(11/11) Installing supervisor (4.2.2-r2)
Executing busybox-1.33.1-r2.trigger
OK: 70 MiB in 47 packages
/ #
/ # supervisorctl
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 10, in <module>
    from importlib.metadata import distribution
  File "/usr/lib/python3.9/importlib/metadata.py", line 5, in <module>
    import csv
  File "/usr/lib/python3.9/csv.py", line 7, in <module>
    from _csv import Error, __version__, writer, reader, register_dialect, \
ModuleNotFoundError: No module named '_csv'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 15, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 23, in <module>
    import zipfile
  File "/usr/lib/python3.9/zipfile.py", line 6, in <module>
    import binascii
ModuleNotFoundError: No module named 'binascii'
```

**Comment by tianon** [comment]
That's interesting -- there isn't anything here that _should_ break that, but I can't reproduce with a stock `alpine:3.14` image so there's gotta be _something_ unique to our image which makes this not work. :confused:

**Comment by tianon** [comment]
The simplest workaround (and the one that will avoid two copies of Python in your image, so frankly "fix" is a better word than workaround) is to use `pip install supervisor==4.2.2` instead of `apk add` -- as far as I can tell, this is technically a bug in Alpine's `python3` package where it gets thrown off by the Python install in `/usr/local` for some reason (even though it shouldn't).

I built a copy of the 3.9 image on Debian Bullseye (which also includes Python 3.9) so I can test there and see if I can reproduce the same behavior on Debian.  I was not able to reproduce in Debian, so this has to be something particular to Alpine, musl, or one of the patches in https://git.alpinelinux.org/aports/tree/main/python3?h=3.14-stable. :confused:
