### ISSUE TITLE
Vulnerabilities "CVE-2021-36222"  found against alpine versions of python

### ISSUE THREAD

**Issue by Bhushanb333** [docker-library/python#627]
Hi,

Vulnerabilities "CVE-2021-36222" found against various alpine versions of python3.7.

This seems to be an additional strict check proposed, active since last 2 days.
Request to provide some help around the resolution of the same.

Thanks,

**Comment by eugine** [comment]
I confirm the issue with 3.9.6 (both alpine3.13 and alpine 3.14 images). 

Some investigation that I did: 
```
[HIGH - CVE-2021-36222] krb5: sending a request containing a PA-ENCRYPTED-CHALLENGE padata element without using FAST could result in null dereference in the KDC which leads to DoS in krb5-libs-1.18.3-r1
	Fixed versions: 1.18.4-r0
```
The fix for the issue in krb5: 
https://github.com/krb5/krb5/releases/tag/krb5-1.18.4-final

Alpine repo for 3.13 and 3.14 has krb5-1.18.4 for both versions (3.14 and 3.13): 
https://pkgs.alpinelinux.org/packages?name=krb5&branch=v3.14
https://pkgs.alpinelinux.org/packages?name=krb5&branch=v3.13

**Comment by tumbl3w33d** [comment]
I also ran into this and was surprised that such dependency actually exists in the container. Could this be made optional or removed entirely?

**Comment by yosifkit** [comment]
> Though not every CVE is removed from the images, we take CVEs seriously and try to ensure that images contain the most up-to-date packages available within a reasonable time frame
>
> \- https://github.com/docker-library/faq/tree/6138d05aabf61563606d86f98d0ccbd99f162b33#why-does-my-security-scanner-show-that-an-image-has-cves

Since our build system makes heavy use of Docker build cache, just rebuilding the all of the alpine-based python Dockerfiles won't cause any change. So we rely on periodic base image updates.

> We strive to publish updated images at least monthly for Debian and Ubuntu. We also rebuild earlier if there is a critical security need. Many Official Images are maintained by the community or their respective upstream projects, like Alpine and Oracle Linux, and are subject to their own maintenance schedule.
>
> \- from the same FAQ link

----

> Could this be made optional or removed entirely?

Not without Alpine changing their packages. The package is not installed explicitly in the [Dockerfile](https://github.com/docker-library/python/blob/95ac9a1746f48d1dcc0318c6901add835ee586c2/3.9/alpine3.14/Dockerfile) so it is a dependency of another package that is kept (`libtirpc-dev` -> `krb5-dev` -> `krb5-libs`)

```console
$ docker pull python:3.9-alpine3.14
3.9-alpine3.14: Pulling from library/python
5843afab3874: Already exists 
2dfaacf7024e: Pull complete 
2dbba127c6aa: Pull complete 
1a467efa2204: Pull complete 
728751b4406e: Pull complete 
Digest: sha256:3fac4a8ca1926c5a0b8fc7165079a58c7868f2b46e2acc263469b4c2fcab68fa
Status: Downloaded newer image for python:3.9-alpine3.14
docker.io/library/python:3.9-alpine3.14
/ # apk del krb5-libs
World updated, but the following packages are not removed due to:
  krb5-libs: .python-rundeps

/ # apk info --all .python-rundeps
.python-rundeps-20210629.193729 description:
virtual meta package
...
.python-rundeps-20210629.193729 depends on:
so:libbz2.so.1
so:libc.musl-x86_64.so.1
so:libcrypto.so.1.1
so:libexpat.so.1
so:libffi.so.7
so:libgdbm.so.6
so:libgdbm_compat.so.4
so:liblzma.so.5
so:libncursesw.so.6
so:libnsl.so.2
so:libpanelw.so.6
so:libreadline.so.8
so:libsqlite3.so.0
so:libssl.so.1.1
so:libtirpc.so.3
so:libuuid.so.1
so:libz.so.1
```

**Comment by wglambert** [comment]
As mentioned in your other thread on a separate CVE https://github.com/docker-library/python/issues/629 the updated packages with their respective patches will be included in the image update and pushed to the Dockerhub shortly https://github.com/docker-library/official-images/pull/10646

In the future note that unless a CVE is of a critical severity the images will be updated on their usual schedule (within a reasonable timeframe, generally at least monthly). And you can always update the images yourself through `apt` or `apk`, such as making your own Dockerfile `FROM python` or otherwise going into the created container and updating any packages manually as a one-off
