### ISSUE TITLE
Entrypoint to install requirements.txt

### ISSUE THREAD

**Issue by mick88** [docker-library/python#628]
Should this image be able to install packages from mounted requirements.txt files?

I use python image to run some command line tools that are not part of python distribution. Currently I have to run the pip install command myself: `docker run python "pip install poeditor-sync && poeditor pull"`. Being able to use the standardised requirements.txt would simplify working with containers with multiple dependencies. Alternatively I'd have to build a separate image for each tool I'm using. The problem here is I would need a place to host the image or build it every time.

Python image could detect that requirements.txt file was mounted and install the dependencies in its entrypoint.
Some docker images already allow mounting init scripts and directories:
Postgres image runs sh scripts from `/docker-entrypoint-initdb.d/`
https://github.com/docker-library/postgres/blob/master/9.6/buster/docker-entrypoint.sh
nginx also has an entrypoint.d directory that contains scripts ran in an entrypoint:
https://github.com/nginxinc/docker-nginx/blob/master/entrypoint/docker-entrypoint.sh

This change would simplify using the image to run scripts that are not bundled in Python by default.
Alternatively, how about an environment variable that will contain packages to be installed in entrypoint?

**Comment by yosifkit** [comment]
No, this is not something we would want to add to our maintenance of the image. There is currently no entrypoint script. Anything added to an entrypoint adds complexity for both the maintainers of the image as well as its consumers. We strive to have the python images represent a "vanilla" python install: being as close to upstream source releases as possible.

The examples of `mysql`, `postgres`, `nginx`, and others are service containers where the intent is clear (start up the server daemon), whereas the python image is a general purpose language base that doesn't have a universal intent. 

If you have a `requirements.txt` then you really need to be building an image that then contains your dependencies rather than hoping that downloading dependencies on-the-fly at every startup is going to continue to work indefinitely.  Public registries, like http://hub.docker.com/ and https://ghcr.io, offer free hosting of public images (and even some private images) and services like GitHub Actions can enable the image to be periodically rebuilt for base image updates or software bumps.
