### ISSUE TITLE
CVE-2021-36159 Introduced through apk-tools@2.10.6-r0

### ISSUE THREAD

**Issue by Bhushanb333** [docker-library/python#629]
Hi,

Vulnerabilities "CVE-2021-36159" found against various alpine versions of python3.7.

Introduced through apk-tools/apk-tools@2.10.6-r0, still persist 
Request to provide some help around the resolution of the same, Posting my findings here.

Vulnerable module: apk-tools/apk-tools
Introduced through: apk-tools/apk-tools@2.10.6-r0
Fixed in: 2.10.7-r0

Thanks,

**Comment by wglambert** [comment]
That CVE's fixed upstream in the package, https://git.alpinelinux.org/aports/commit/?id=d5c49fa3c576f95021d05ebe1127b7946ce0a093 
There's a PR open for the latest commits that will include the updated packages and the fix for the CVE https://github.com/docker-library/official-images/pull/10646

See also https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves
