### ISSUE TITLE
kubernetes-pod-fails-with-crashloopbackoff 🔴 

### ISSUE THREAD

**Issue by vivek-vijayan** [docker-library/python#648]
When I do pull the python to kubernetes, the pod get fails and shows crashloopbackoff.

**Comment by wglambert** [comment]
I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). And providing the commands you ran and any relevant files or logs, since these repos aren't really a user-help forum

**Comment by yosifkit** [comment]
Just a random guess but unless you are running a specific python file that is a service of some sort, then the default of this image is to run an interactive python shell that would exit immediately in a default kubernetes pod because there is no TTY (i.e. an interactive user).

https://github.com/docker-library/python/blob/50850bb077be358026bfc240adcbcbc850a5bd33/3.9/bullseye/Dockerfile#L100
