### ISSUE TITLE
Why is Python installed to /usr/local/bin/python3?

### ISSUE THREAD

**Issue by hwittenborn** [docker-library/python#671]
I just got started using the image, and I noticed that Python is installing to files like `/usr/local/bin/python3` by default. Is there any reason for doing so?

The issue mostly came into play when I was using a `#!/usr/bin/python3` shebang at the top of one of my scripts, after which I noticed imports were just straight-up not working after installing some dependencies with Pip.

It's not really an issue if you can figure out how to fix the issue (running `type python3` manually in a container revealed the issue for me), though I suspect that some users might end up spending quite a bit of time on it.

Perhaps there could be symlinks to `/usr/local/bin` for the Python executables (i.e. `/usr/bin/python3` to `/usr/bin/python3.10` on the current `latest` tag)? I'm seeing that they go to Debian-installed executables by default (`/usr/bin/python3` goes to `/usr/bin/python3.9` at least), but I don't see any benefit provided by that.

**Comment by yosifkit** [comment]
`/usr/local/` is used to prevent system packages from accidentally overwriting the source installed python provided by the image (https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html). If we change the symlinks (via something like `dpkg-divert`), then we could likely break system tools (like `apt`) by providing an incompatible `python3`.

Rather than assuming the location of the `python3` executable in your scripts, you can use `env` to find the preferred executable. So I think the universal shebang would be `#!/usr/bin/env python3`.
