### ISSUE TITLE
SSL Handshake Error Only in Docker and Selenium trying to access website

### ISSUE THREAD

**Issue by thlorenzen** [docker-library/python#725]
I have a python script which is running Chrome with chromedriver and selenium. When I run the script without Docker it works normally and I access the website, if in Docker the Exception gets shown in the Browser with a 502 Gateway Error. My theory is that I need to configure the SSl Settings in the Docker Container, but I dont know exactly how.
Error shown in Chrome in Docker(Selenium):
`TlsProtocolException('Cannot establish TLS with accounts.ea.com:443 (sni: accounts.ea.com): 
TlsException("SSL handshake error: Error([(\'SSL routines\', \'\', \'unsafe legacy renegotiation disabled\')])")')```
`

**Comment by wglambert** [comment]
It could be different default settings for the openssl in the container vs. the host's version of it

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
