### ISSUE TITLE
CVE-2021-46828

### ISSUE THREAD

**Issue by tooptoop4** [docker-library/python#743]
Installed Resource libtirpc 1.3.2-r0 in python:3.10.5-alpine3.16

https://github.com/docker-library/python/blob/master/3.10/alpine3.16/Dockerfile#L43

can it be removed?

**Comment by yosifkit** [comment]
I don't think so. We check all build dependencies for whether they were linked to by something built and if it is still in the final image, then something is linking to it (or an `apk` dependency of it). This bit is making sure anything that provides an  `.so` that is linked to is kept after we remove the temporary `.build-deps` defined/installed earlier:

https://github.com/docker-library/python/blob/6ca54f5e8a180fad4b525c2dfecd23c76ff04894/3.10/alpine3.16/Dockerfile#L101-L107

`libnsl-dev` depends on `libtirpc-dev`, so to get rid of `libtirpc-dev`, we also have to remove `libnsl-dev`. It looks like these are both linked to by the `nis` module:
```console
/ # find /usr/local -type f -executable -not \( -name '*tkinter*' \) -exec scanelf --needed --nobanner --format '%p%n#p' '{}' ';' | grep rpc
/usr/local/lib/python3.10/lib-dynload/nis.cpython-310-x86_64-linux-gnu.solibnsl.so.3,libtirpc.so.3,libc.musl-x86_64.so.1
```

Which is only just now being deprecated with a warning starting in Python `3.11` (https://peps.python.org/pep-0594/) and won't be removed until Python `3.13`.

**Comment by raoganeshr** [comment]
Will this be fixed in the next image refresh? If yes, when is it planned?

**Comment by rasulkireev** [comment]
Looks like you can bypass that by installing latest versions in your Dockerfile:

```
RUN apt-get install libtirpc3=1.3.1-1+deb11u1 libtirpc3=1.3.1-1+deb11u1 -yqq
```

**Comment by yosifkit** [comment]
> Will this be fixed in the next image refresh? If yes, when is it planned?

For the Alpine-based images, today. Since the base images were just updated in https://github.com/docker-library/official-images/pull/12929, the dependent images will be rebuilt in the coming hours.

For the Debian-based images, probably in 3 weeks or so since the last rebuild was only 8 days ago (https://github.com/docker-library/official-images/pull/12889).

**Comment by tooptoop4** [comment]
@yosifkit isn't the base image update for a different CVE, not CVE-2021-46828?

**Comment by yosifkit** [comment]
> @yosifkit the base image update is for a different CVE, i confirmed `CVE-2021-46828` **is still in** python:3.10.6-alpine3.16 from couple hours ago

Yes, the base was updated for a specific different CVE, but since we rebuild all dependent official images when a parent image changes, the Alpine-based python images will naturally get any security fixes of packages installed in their layers. https://security.alpinelinux.org/vuln/CVE-2021-46828 shows that for Alpine 3.16, the `1.3.2-r1` contains the fix, which is the version in the most recent image:

```console
$ docker run -it --rm python:3.10.6-alpine3.16 sh
Unable to find image 'python:3.10.6-alpine3.16' locally
3.10.6-alpine3.16: Pulling from library/python
213ec9aee27d: Pull complete 
6b2a141cd227: Pull complete 
a292fad6b52e: Pull complete 
4593e4e33a59: Pull complete 
95765f0918ef: Pull complete 
Digest: sha256:db0f3888d0ef4293a6387462b87a75bcdd0c4bc4cfc798ec617a5923be780cf6
Status: Downloaded newer image for python:3.10.6-alpine3.16
/ # apk list | grep tirpc
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/main: No such file or directory
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/community: No such file or directory
libtirpc-conf-1.3.2-r1 x86_64 {libtirpc} (BSD-3-Clause) [installed]
libtirpc-1.3.2-r1 x86_64 {libtirpc} (BSD-3-Clause) [installed]
```
