### ISSUE TITLE
Error: /bin/sh: 1: [python3,: not found with Docker Image Windows

### ISSUE THREAD

**Issue by Nebraw** [docker-library/python#748]
I created the following Docker Image:
```
FROM python:3.6-slim

#Create the directory for the App 
WORKDIR /app

COPY . /app
COPY ./Storm/ /app/Storm/
RUN pip install --user -r requirement.txt

ARG Ip="127.0.0.1"
ARG CorpName="CorpName"
ARG Num =100

CMD ["python3", "Storm.py", "-Ip", Ip, "-CorpName", CorpName, "-nb", Num ]
```
The image is build perfecty, but if i try to run the Image i got the following message:
**/bin/sh: 1: [python3,: not found**

If i replace the CMD by:
**CMD ["python3", "Storm.py"]** 
the run work perfectly

**Comment by yosifkit** [comment]
You cannot use `ARG` or `ENV` values in a json syntax `CMD`. Since some of the parts were not valid `json`, it assumed the line is "shell syntax". If just shell syntax is used, like below, know that the shell (`/bin/sh`) will be given the full line and do the interpolation so it won't have access to any build `ARG`'s defined during build, since the shell only happens when the image is run as a container which  means the `ARG`'s will be no longer defined.

```Dockerfile
CMD ["python3", "Storm.py", "-Ip", Ip, "-CorpName", CorpName, "-nb", Num ]
# since it is not valid json syntax
# results in roughly this being run: sh -c "\[\"python3\", \"Storm.py\", \"-Ip\", Ip, \"-CorpName\", CorpName, \"-nb\", Num \]"


CMD python3 Storm.py -Ip $Ip -CorpName $CorpName -nb $Num
# results in this being run: sh -c "python3 Storm.py -Ip $Ip -CorpName $CorpName -nb $Num"
# if you go this route, I'd recommend adding an `exec` to be certain the shell is gone as the python starts
CMD exec python3 Storm.py -Ip $Ip -CorpName $CorpName -nb $Num
```
---

Could also use `ENTRYPOINT` to some effect:
```dockerfile
ENTRYPOINT ["python3", "Storm.py"]
CMD ["-Ip", "127.0.0.1", "-CorpName", "example", "-nb", "100" ]
```
And then `docker run image` will get the defaults and then to replace the CMD-provided values: `docker run  image -Ip "some-ip" -CorpName new-corp -nb 50`
