### ISSUE TITLE
[REQUEST] dependency updates

### ISSUE THREAD

**Issue by MartinHotmann** [docker-library/python#749]
Please update dependencies of:

PIP [22.2.1](https://pypi.org/project/pip/22.2.1/) ==> [22.2.2](https://pypi.org/project/pip/22.2.2/)
setuptools [63.2.0](https://pypi.org/project/setuptools/63.2.0/) ==> [63.4.2](https://pypi.org/project/setuptools/63.4.2/)

As somehow they are not on the latest version.

Thanks!

**Comment by tianon** [comment]
Unfortunately, this is very intentional - we used to proactively follow updates to these, and it caused a lot of problems for users, so we opted instead to explicitly follow what comes bundled with CPython upstream instead.  See #186, #194, #365, #647 for several related discussions.

Updating these in a dependent image should be reasonably straightforward (`pip install xxx`), whereas downgrading them in a dependent image is usually less straightforward.
