### ISSUE TITLE
put back images for python 3.9 for windows

### ISSUE THREAD

**Issue by koalp** [docker-library/python#769]
Hello, 
I noticed that python 3.9 images for windows have been removed [in a commit made the 7th september](https://github.com/docker-library/python/commit/008e5da2192428c97437191969d9b71a05d8acae) (3.10+ are still available). I wonder why they have been removed and if it is planned to put them back.

**Comment by yosifkit** [comment]
There are no plans to add them back since there are no longer binary installers provided by Python. I found this same removal done previously in https://github.com/docker-library/python/pull/623#issuecomment-870642619 and https://github.com/docker-library/python/pull/259, but now the update.sh process automatically removes them.

> According to the release calendar specified in PEP 596, Python 3.9 is now in the "security fixes only" stage of its life cycle: the 3.9 branch only accepts security fixes and releases of those are made irregularly in source-only form until October 2025. Python 3.9 isn't receiving regular bug fixes anymore, and binary installers are no longer provided for it. Python 3.9.13 was the last full bugfix release of Python 3.9 with binary installers.
>
> \- https://www.python.org/downloads/release/python-3914/

**Comment by tianon** [comment]
Also, the old images are still available to pull, they just won't receive any further updates/rebuilds: https://hub.docker.com/_/python/tags?name=3.9-windows
