### ISSUE TITLE
The image should run with a non root user ?

### ISSUE THREAD

**Issue by cvgaviao** [docker-library/python#804]
Today I requested my company's security team to allow me to use the slim-bullseye image for a project to be run on Openshift.

They denied the request because Twistlock scan have detected an issue:

`Compliancy:   failed:  the image should run with a non root user`

Well, I was not able to argue against it.

**Comment by tianon** [comment]
I agree wholeheartedly that all users of this image should be running it with a non-root user!  However, we cannot set a non-root user by default because it makes it much harder for users to build images based on this one, and also brings up the question of which user we'd set it to -- 1000?  999?  65536?

In this case, the image itself isn't really all that useful to run by _itself_, and you'll almost _always_ have to include some amount of your own application source code inside it (because it's just the raw interpreter / package manager for Python by default), so you'll likely write yourself a short `Dockerfile` for your application which installs any necessary dependencies, copies in your application, and _that_ would then be the appropriate place for you to choose/set a specific user to run your derived image as.

For further help/advice, I would suggest trying a dedicated support forum, such as [the Docker Community Slack](https://dockr.ly/comm-slack), [Server Fault](https://serverfault.com/help/on-topic), [Unix & Linux](https://unix.stackexchange.com/help/on-topic), or [Stack Overflow](https://stackoverflow.com/help/on-topic).
