### ISSUE TITLE
question: using build args for base image

### ISSUE THREAD

**Issue by metasyn** [docker-library/python#818]
🐍 Hello docker-library/python developers,

Firstly, thank you for maintaining such useful software for the rest of us 🙇 

I would like to use these Dockerfiles (not the built images) in a corporate scenario where the base image needs to be coming from an internal registry. Is there any appetite for enabling this type usage of these Dockerfiles by allowing a build arg for the initial `FROM` layer?

Here an example. Currently we have [this](https://github.com/docker-library/python/blob/master/3.10/slim-bullseye/Dockerfile#L7) in the rendered Dockerfile:
```dockerfile
FROM debian:bullseye-slim
```

In my corporate environment, I would like to be able to replace this image with some of our internally managed base images when utilizing this Dockerfile. My proposal, concretely, is the modification here:

```dockerfile
ARG BASE_IMAGE debian:bullseye-slim
FROM $BASE_IMAGE
```

This would have the same resulting image being built in this repo, but would allow others to utilize the great work in this repo even if they require a different base image. At my company, our base images have additional tooling/configurations setup that would be useful to inherit from immediately. With the `BASE_IMAGE` build arg, we would be able to do something like:

```shell
docker build --build-arg BASE_IMAGE=registry.corporation.com/something https://raw.githubusercontent.com/docker-library/python/master/3.10/slim-bullseye/Dockerfile
```

I'm not sure if this is an amenable idea. If this seems like a reasonable change, I am happy to make a PR to add and help test this modification. Thanks for your time.

**Comment by ad-m-ss** [comment]
In my opinion...

Supporting a new base image is not as simple as adding build-arg. This can generate a lot of issues and incompatibilities, and thus an excessive maintenance burden on the side of open-source volunteers. The number of potential images is infinite, and it will be very difficult to recreate the issues.

If corporations tell you to use their base image, I suggest you ask your IT department to prepare and maintain its own local base image for Python. The open-source image for Python here can be an inspiration, but it should be maintained by your IT department since it has such specialized requirements. It is worth considering how the base image they recommend was prepared, because - for examlpe – as [Red Hat prepared it](https://developers.redhat.com/blog/2020/03/24/red-hat-universal-base-images-for-docker-users#introducing_red_hat_universal_base_images) (some corporations likes to use Red Hat), Red Hat also has its own [base Python image](https://catalog.redhat.com/software/containers/ubi9/python-39/61a61032bfd4a5234d59629e).

**Comment by metasyn** [comment]
Ah I can see that perspective - I was not thinking of this repo "supporting" infinite base images, just because its doable. For example, if I just decided to currently run `docker build <remote-url>` and it happens to point to this URL, I don't think this repo would be expected to "support" all the different runtime flags that can be provide to `docker build`. By the same logic, I could come up with tons of failing and unsupported approaches with the existing Dockerfile - like incorrectly modifying the user, group, mounting files into a needed location, and so on, but the maintainers of this repo aren't expected to have anything to do with _my invocation_ of `docker build`. To summarize, I definitely agree that that any change that creates an excessive burden on the open-source volunteers is a non-starter, but don't think that every invocation flag to docker build is expected to be supported, and this proposal falls under adding a flag that _could_ be used, but isn't necessarily used (by this repo).

> If corporations tell you to use their base image, I suggest you ask your IT department to prepare and maintain its own local base image for Python.

I am representing that group of people 😂 and did use code in this repo for inspiration for compiling our own base image internally. However, some of my team members asked about ways to reduce the amount of copied code by making this code more reusable in other contexts (which is the main reason I asked the question). In terms of the specialized requirements, it's actually primarily using Ubuntu rather than Debian. Related, I saw that https://github.com/docker-library/python/pull/791 was open and when this is merged it may alleviate some of the issues, however, even in that case, it would be nice to use our internal image for Ubuntu 22.04 rather than the base one suggested in that PR. One other related thing we needed to change to make this work is the addition of proxy variables to the gpg keyserver options (to get around/through our firewall).

Overall, I'm still curious if the `ARG BASE_IMAGE` modification could be considered, given the caveat that arbitrary values to that build arg would not be "supported" in the same way that adding other arbitrary flags and values to the `docker build` invocation (e.g. `-v /usr/bin/:/usr/bin -u 100 -g 100`) isn't "supported", or expected to be.

**Comment by tianon** [comment]
Unfortunately, the downstream Docker Official Images build tooling does not support build args for the base image definition because it needs to be able to enumerate the full build dependency tree, and build args make that more complicated.

From a purely pragmatic perspective, I'm not sure I see significant difference between `--build-arg BASE_IMAGE=...` when building this `Dockerfile` that you'd already likely have to have locally vs actually editing the `Dockerfile` itself (`sed -i -e 's/^FROM .*/FROM xxx/' Dockerfile` for a very quick-and-dirty version that I've used variations of in other use cases).

Additionally, along the same lines as what's been raised, while our `Dockerfile` _technically_ works as-is in quite a few different base distros (notably `ubuntu`), it is definitely not supported by us and we would absolutely close issues discussing Ubuntu-specific problems, and I do worry that a build arg that helps enable users doing that sends a mixed message about that level of support (because unlike your `-v`/`-u` example, it's something explicit that we would add that's _designed_ for user specified values, not something just inherent to the platform -- the difference between the "off-road trail" existing vs us advertising that it exists and building an on-ramp onto it :speak_no_evil:).

You might also be interested in BuildKit's `--build-context` flag, which allows for horrifying things like `--build-context debian:bullseye-slim=docker-image://ubuntu:22.04` :eyes: :grimacing: :sweat_smile:
