### ISSUE TITLE
Not able to import pandas in docker container using python:3.8

### ISSUE THREAD

**Issue by YaswanthDara** [docker-library/python#848]
```
Linux machine:- Rocky Linux 8.5
Docker version:- 24.0.2 
```

Dockerfile 
```
FROM python:3.8

RUN apt-get update && apt-get install -y vim
RUN apt-get update && \
    apt-get install -y python3-venv && \
    python3 -m venv gdmt_venv && \
    . gdmt_venv/bin/activate && \
    pip install --upgrade pip

RUN python3 -m pip install --trusted-host pypi.python.org -r requirements.txt
WORKDIR /app
```
<img width="881" alt="Screenshot 2023-07-03 at 10 43 55 AM" src="https://github.com/docker-library/python/assets/85473312/02eaaf6f-2d41-49e8-a919-3cf58378e73f">

I tried importing pandas inside the docker image using the python shell and got same issue.

**Comment by ad-m-ss** [comment]
Do you think it may be related to https://github.com/docker-library/python/issues/835 ?

**Comment by tianon** [comment]
Yep, looks likely!  (`pthread_create` getting EPERM)

**Comment by YaswanthDara** [comment]
hey @tianon , @ad-m-ss  this image had issues only while importing pandas. can you give a solution to this. Thanks

**Comment by ad-m-ss** [comment]
Which solutions shared in the linked thread have you tested And what results have you achieved?

**Comment by YaswanthDara** [comment]
I tried some of solutions given by chatgpt and found in online, like updating the docker version on system and updating some libraries.. but any of the above didn’t solve the issue..

**Comment by tianon** [comment]
The underlying issue is a seccomp denial and the correct fix is to ensure your host's versions of `libseccomp2`, Docker, and runc are all appropriately new enough.

For further help figuring out the exact details of what that means in your specific environment, I would really suggest a dedicated support forum, such as [the Docker Community Slack](https://dockr.ly/comm-slack), [Server Fault](https://serverfault.com/help/on-topic), [Unix & Linux](https://unix.stackexchange.com/help/on-topic), or [Stack Overflow](https://stackoverflow.com/help/on-topic).

For our tracking purposes, I'm going to close this as a duplicate of https://github.com/docker-library/python/issues/835.
