### ISSUE TITLE
Feat: include git in windows images

### ISSUE THREAD

**Issue by mutricyl** [docker-library/python#928]
I am using python docker image for my windows gitlab runner and I would need to use git and python within my gitlab pipelines.

My docker skills are very limited and I would not be confident storing my experimental image on dockerhub.

As windows pyhton image are already quite large in size, I seems to me that adding git by default is not such a big deal. So I was wondering if you could include git in you windows images?

**Comment by tianon** [comment]
Thanks for the request!  Unfortunately, I don't think I'm comfortable adding this, but you might take inspriration from https://github.com/docker-library/golang/blob/eb57429622f401af7c5afffeb3cd88022c9b9782/1.22/windows/windowsservercore-ltsc2022/Dockerfile#L12-L44 in adding it to your own images.

(Even that installation is something we should reconsider given that Go prefers to use the proxy instead of Git now.)

**Comment by mutricyl** [comment]
Ok, thanks for the tip.
