### ISSUE TITLE
Problem with expat docker-image 3.11.10-slim

### ISSUE THREAD

**Issue by walidzz** [docker-library/python#965]
When pulling image docker-image 3.11.10-slim, I still have the old version of expat: 
```
import xml.parsers.expat
xml.parsers.expat.EXPAT_VERSION
'expat_2.5.0'
```

Which has a high vulnerability. Can you please help with this.
I need the last version 2.6.3 :)

**Comment by LaurentGoderre** [comment]
That version is not available yet for bookworm.

**Comment by tianon** [comment]
> Which has a high vulnerability.

Do you have details about _which_ vulnerability?  Is this picked up by a scanner or something you've successfully exploited?

See also https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves, where I think the most likely case is probably:

> In order to provide stability, most OS distributions take the fix for a security flaw out of the most recent version of the upstream software package and apply that fix to an older version of the package (known as backporting).

Also a high chance it's:

> The OS Security team only has so much available time and has to deprioritize some security fixes over others. This could be because the threat is considered low or that it is too intrusive to backport to the version in "stable".

See also https://security-tracker.debian.org/tracker/source-package/expat

**Comment by walidzz** [comment]
It is picked up by the default docker desktop scanner and by the AWS one.
![Screenshot 2024-09-12 at 09 57 14](https://github.com/user-attachments/assets/5ef8c6c2-44e7-4d65-a7b5-4428a1620325)

**Comment by tianon** [comment]
- https://security-tracker.debian.org/tracker/CVE-2024-45492 - not fixed in Debian (the second case I highlighted)
- https://security-tracker.debian.org/tracker/CVE-2024-45491 - the same
- https://security-tracker.debian.org/tracker/CVE-2024-45490 - again, the same
- https://security-tracker.debian.org/tracker/CVE-2024-28757 - same, includes a note that it's not an Expat vuln so much as a vuln in apps _using_ Expat
- https://security-tracker.debian.org/tracker/CVE-2023-52426 - same, includes a note that this does not apply to Debian (although not annotated in the correct way, so Scout didn't pick it up properly)

https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves

**Comment by yosifkit** [comment]
So, partially a duplicate of https://github.com/docker-library/python/issues/959. Since this isn't fixed in Debian packages, there is not much we can do.

**Comment by Pebin** [comment]
is seems like these there

https://security-tracker.debian.org/tracker/CVE-2024-45492
https://security-tracker.debian.org/tracker/CVE-2024-45491
https://security-tracker.debian.org/tracker/CVE-2024-45490

have been pushed to bookworm security yesterday. It's not really the 2.6.3 version just some cherrypick to 2.5.0
https://tracker.debian.org/pkg/expat

**Comment by yosifkit** [comment]
> It's not really the 2.6.3 version just some cherrypick to 2.5.0

That's how stable distributions like Debian, RedHat, and Ubuntu work. They backport just security fixes in order to provide stable libraries for the life of the distribution release (with some being more or less willing to fudge the line of what is and isn't acceptable in a "stable" update).

Given that there are fixes available, the `python` images will get the update as soon as there is a change in the python image that would break the build cache or when the base image updates.

---

Background: 
>Tags in the [official-images] library file[s] are only built through an update to that library file or as a result of its base image being updated (ie, an image `FROM debian:bookworm` would be rebuilt when `debian:bookworm` is built). 
>
>\-https://github.com/docker-library/official-images/tree/2f086314307c04e1de77f0a515f20671e60d40bb#library-definition-files

Official Images FAQ:

> Though not every CVE is removed from the images, we take CVEs seriously and try to ensure that images contain the most up-to-date packages available within a reasonable time frame
>
> \- https://github.com/docker-library/faq/tree/0ad5fd60288109c875a54a37f6581b2deaa836db#why-does-my-security-scanner-show-that-an-image-has-cves

To ensure that we don't push contentless image changes, we rely on periodic base image updates.

> We strive to publish updated images at least monthly for Debian. We also rebuild earlier if there is a critical security need. Many Official Images are maintained by the community or their respective upstream projects, like Ubuntu, Alpine, and Oracle Linux, and are subject to their own maintenance schedule.
>
> \- from the same FAQ link
